# This is a basic workflow to help you get started with Actions
name: build
# Controls when the workflow will run
on:
  #push:
    #branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: build the main thingy
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3 # what does this do lol

      # Runs a set of commands using the runners shell
      - name: Build SteamDD.bat
        run: |
          echo preparing
          echo %cd%
          C:
          cd \
          mkdir EZDD_build
          curl https://raw.githubusercontent.com/WilliamAnimate/EZDD-build-experiment/main/EZDD_Build/Bat_To_Exe_Converter_x64.exe -o C:\EZDD_build\b2e.exe
          curl https://raw.githubusercontent.com/WilliamAnimate/EZDD-build-experiment/main/SteamDD.bat -o C:\EZDD_build\SteamDD.bat
          echo BUILDING..
          C:\EZDD_build\b2e.exe /bat C:\EZDD_build\SteamDD.bat /exe C:\EZDD_build\SteamDD.exe /x64 & timeout 6 & taskkill /f /im b2e.exe
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
            # Artifact name
            name: artifact
            # A file, directory or wildcard pattern that describes what to upload
            path: C:\EZDD_build 
            # placeholder path, not just the path but the ENTIRE FOLDER
        #Available Options:
            #warn: Output a warning but do not fail the action

            if-no-files-found: warn
            retention-days: 5
