# This is a basic workflow to help you get started with Actions
name: build
# Controls when the workflow will run
on:
  #push:
    #branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: setup
    runs-on: windows-latest
    
    # todo: make this bs run on cmd or powershell
    # running on cmd is potentally better since ps takes a bit longer to start
    # HOWEVER.. IF we require using powershell at any point, we start with ps.
    # IF ps is the only option left, the name of the game is "throw random sh- at the wall"
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: prepare build env
        shell: cmd
        run: |
          echo "preparing to run and stuff"
          C:
          cd \
          mkdir EZDD_build
          curl https://raw.githubusercontent.com/WilliamAnimate/EZDD-build-experiment/main/EZDD_Build/Bat_To_Exe_Converter_x64.exe -o C:\EZDD_build\b2e.exe
          curl https://raw.githubusercontent.com/WilliamAnimate/EZDD-build-experiment/main/SteamDD.bat -o C:\EZDD_build\SteamDD.bat
      #- name: build EZDD main
       # run: |
        #  echo "asdf"
      - name: Build and run b2e.exe
        run: |          
          echo BUILDING at %cd%
          .\EZDD_BUILD\b2e.exe /bat SteamDD.bat /exe ${{ github.workspace }}/EZDD_Build/SteamDD.exe & ping -n 1 -w 15000 127.0.0.1 & taskkill /f /im b2e.exe
          
      - uses: stefanzweifel/git-auto-commit-action@v4


